config/routes.rb
Foswipe::Engine.routes.draw do
  resources :user_chats

  resources :user_groups

  

  resources :tickets do
    resources :todos
    resources :comments
    post :create_from_email, :on => :collection
  end

  resources :comments

  resources :purchases

  resources :products

  resources :organizations

  devise_for :users, class_name: "Foswipe::User", module: :devise

  resources :tickets do
    get :all_tickets, :on => :collection
  end

  resources :supports

  resources :clients do
    resources :tickets
  end

  resources :projects

  resources :users

  resources :admins

  root 'admins#index'
  #post '/assign_tickets_to_supports' => 'admins#assign_tickets_to_supports'
  post '/assign_support_notes_to_tickets' => 'supports#assign_support_notes_to_tickets'

end

app/models/foswipe/attachment.rb
module Foswipe
  class Attachment < ActiveRecord::Base
    belongs_to :attachable, :polymorphic => true
    dragonfly_accessor :attachment
  end
end

app/models/foswipe/comment.rb
class Foswipe::Comment < ActiveRecord::Base
  belongs_to :ticket
  belongs_to :user
  #has_many :attachments

  has_many :attachments, :dependent => :destroy, :as => :attachable
  accepts_nested_attributes_for :attachments

end

app/models/foswipe/concerns/filterable.rb
module Foswipe
  module Concerns
    module Filterable
      extend ActiveSupport::Concern

      module ClassMethods
        def filter(filtering_params)
          results = self.where(nil)
          filtering_params.each do |key, value|
            results = results.public_send(key, value) if value.present?
          end
          results
        end
      end
    end
  end
end

app/models/foswipe/organization.rb
class Foswipe::Organization < ActiveRecord::Base
  has_many :purchases
  has_many :users
  has_many :slas, :as => :slas
end

app/models/foswipe/product.rb
class Foswipe::Product < ActiveRecord::Base
  has_many :purchases
end

app/models/foswipe/purchase.rb
class Foswipe::Purchase < ActiveRecord::Base
  belongs_to :organization
  belongs_to :product
end

app/models/foswipe/sla.rb
module Foswipe
  class Sla < ActiveRecord::Base
    belongs_to :slas, :polymorphic => true
  end
end

app/models/foswipe/ticket.rb
class Foswipe::Ticket < ActiveRecord::Base
  include Foswipe::Concerns::Filterable

  belongs_to :customer , :class_name => :User,:foreign_key => "client_id"
  belongs_to :agent , :class_name => :User,:foreign_key => "support_id"
  has_many :comments
  belongs_to :user_group
  has_many :todos, :dependent => :destroy

  accepts_nested_attributes_for :comments
  has_many :attachments, :dependent => :destroy, :as => :attachable

  accepts_nested_attributes_for :attachments

  scope :agents, -> support { where(:support_id =>  support) }
  scope :groups, -> group { where(:user_group_id =>  group) }
  scope :status, -> status { where(:status =>  status) }
  scope :ticket_type, -> ticket_type { where(:user_group_id =>  ticket_type) }
  scope :source, -> source { where(:user_group_id =>  source) }
  scope :priority, -> priority {where(:priority => priority)}
  scope :search, -> search {where("content LIKE ? OR title LIKE ? ", "%#{search}%", "%#{search}%")}

  scope :priorities, -> { ["LOW","MEDIUM","HIGH","URGENT"] }
  scope :statuses, -> { ["Open","Pending","Resolved","Closed","Waiting on Customer","Waiting on Third Party"] }

  scope :created_at, -> created_at do
    where(:created_at => eval(created_at)) if eval(created_at).class == Range
  end
  
  def ticket_comments
    comments.where(:type => "Foswipe::TicketComment")
  end
  
  def ticket_notes
    comments.where(:type => "Foswipe::TicketNote")
  end

end

app/models/foswipe/ticket_comment.rb
class Foswipe::TicketComment < Foswipe::Comment
  
end

app/models/foswipe/ticket_note.rb
class Foswipe::TicketNote < Foswipe::Comment
end

app/models/foswipe/todo.rb
module Foswipe
  class Todo < ActiveRecord::Base
    belongs_to :ticket
  end
end

app/models/foswipe/user_chat.rb
module Foswipe
  class UserChat < ActiveRecord::Base
    belongs_to :customer, :foreign_key => "customer_id", :class_name => "User"
    belongs_to :agent, :foreign_key => "agent_id", :class_name => "User"
  end
end

app/models/foswipe/user_group.rb
module Foswipe
  class UserGroup < ActiveRecord::Base
    has_and_belongs_to_many :users
    accepts_nested_attributes_for :users
    has_many :tickets
  end
end

app/controllers/foswipe/admins_controller.rb
class Foswipe::AdminsController < Foswipe::ApplicationController
  before_action :set_admin, only: [:show, :edit, :update, :destroy]
  before_action :authorise_filter, :only => [:index, :new, :create]

  # GET /admins
  # GET /admins.json
  def index
    @admins = Foswipe::User.admins
  end

  # GET /admins/1
  # GET /admins/1.json
  def show
  end

  # GET /admins/new
  def new
    @admin = Foswipe::User.new
  end

  # GET /admins/1/edit
  def edit
  end

  # POST /admins
  # POST /admins.json
  def create
    @admin = Foswipe::User.new(user_params)
    @admin.admin = true
    respond_to do |format|
      if @admin.save
        format.html { redirect_to admins_url, notice: 'Admin was successfully created.' }
        format.json { render action: 'show', status: :created, location: @admin }
      else
        format.html { render action: 'new' }
        format.json { render json: @admin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admins/1
  # PATCH/PUT /admins/1.json
  def update
    respond_to do |format|
      if @admin.update(user_params)
        format.html { redirect_to admins_url, notice: 'Admin was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @admin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admins/1
  # DELETE /admins/1.json
  def destroy
    @admin.destroy
    respond_to do |format|
      format.html { redirect_to admins_url }
      format.json { head :no_content }
    end
  end

  def assign_tickets_to_supports
    Ticket.find(params[:ticket][:ticket_id]).update(:support_id => params[:ticket][:support_id])
    respond_to do |format|
      format.html { redirect_to admins_url, notice: 'Successfully assigned to support team.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin
      @admin = Foswipe::User.find(params[:id])
      authorise_filter @admin
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    
end

app/controllers/foswipe/application_controller.rb
module Foswipe
  class ApplicationController < ActionController::Base
    include Pundit
    protect_from_forgery
    before_action :authenticate_user!
    #after_action :verify_authorized
    def after_sign_in_path_for(resource)
      if current_user.admin?
        admin_tickets_path
      elsif current_user.agent?
        supports_path
      elsif curent_user.customer?
        clients_path
      end
    end

    def authorise_filter(record = nil)
      policy = (params[:controller][0..-1] + "_policy").classify.constantize.new(current_user,record)
      query = params[:action].to_s + "?"
      unless policy.public_send(query)
        redirect_to :back, notice: 'not allowed'
      end
    end
    def user_params
      params.require(:user).permit(:name, :email, :first_name, :last_name, :password, :password_confirmation, :mobile_no, :address, :organization_id)
    end

  end
end

app/controllers/foswipe/clients_controller.rb
class Foswipe::ClientsController < Foswipe::ApplicationController
  before_action :set_client, only: [:show, :edit, :update, :destroy]
  before_action :authorise_filter, :only => [:index, :new, :create]

  # GET /clients
  # GET /clients.json
  def index
      @clients = Foswipe::User.customers
      #@tickets = current_user.tickets if current_user.customer?
  end

  # GET /clients/1
  # GET /clients/1.json
  def show
    #@ticket = @client.tickets.new
    @tickets = @client.tickets
  end

  # GET /clients/new
  def new
    @client = Foswipe::User.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients
  # POST /clients.json
  def create
    @client = Foswipe::User.new(user_params)
    respond_to do |format|
      if @client.save
        format.html { redirect_to clients_url, notice: 'Client was successfully created.' }
        format.json { render action: 'show', status: :created, location: @client }
      else
        format.html { render action: 'new' }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1
  # PATCH/PUT /clients/1.json
  def update
    respond_to do |format|
      if @client.update(user_params)
        format.html { redirect_to clients_url, notice: 'Client was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    @client.destroy
    respond_to do |format|
      format.html { redirect_to clients_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Foswipe::User.find(params[:id])
      authorise_filter @client
    end
end

app/controllers/foswipe/comments_controller.rb
class Foswipe::CommentsController < Foswipe::ApplicationController
  before_action :set_comment, only: [:show, :edit, :update]
  before_action :authorise_filter, :only => [:index, :new, :create]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Foswipe::TicketComment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
    
  end

  # GET /comments/new
  def new
    #@ticket = Ticket.new
    @comment = Comment.new
    comment_attachment = @comment.attachments.build
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @ticket = Foswipe::Ticket.find(params[:ticket_id])
    @comment = @ticket.comments.new(comment_params)
    @comment.user = current_user

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @ticket, notice: 'Comment was successfully created.' }
        format.json { render action: 'show', status: :created, location: @comment }
      else
        format.html { render action: 'new' }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end
  

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
   # @ticket = Ticket.find(params[:ticket_id])
    #puts @ticket
   # @comment = @ticket.comments
    #puts "hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh"
   # puts @comment
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to @ticket, notice: 'Comment was successfully deleted' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Foswipe::TicketComment.find(params[:id])
      authorise_filter @comment
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:content, :user_id, :type, :attachments_attributes => [:attachment])
    end
    
end

app/controllers/foswipe/organizations_controller.rb
class Foswipe::OrganizationsController < Foswipe::ApplicationController
  before_action :set_organization, only: [:show, :edit, :update, :destroy]
  before_action :authorise_filter, :only => [:index, :new, :create]
  # GET /organizations
  # GET /organizations.json
  def index
    if current_user.customer?
      redirect_to current_user.organization
    else
      @organizations = Foswipe::Organization.all
    end

  end

  # GET /organizations/1
  # GET /organizations/1.json
  def show
  end

  # GET /organizations/new
  def new
    @organization = Foswipe::Organization.new
  end

  # GET /organizations/1/edit
  def edit
  end

  # POST /organizations
  # POST /organizations.json
  def create
    @organization = Foswipe::Organization.new(organization_params)

    respond_to do |format|
      if @organization.save
        @organizations = Foswipe::Organization.all
        format.html { render action: 'index', notice: 'Organization was successfully created.' }
        format.json { render action: 'show', status: :created, location: @organization }
      else
        format.html { render action: 'new' }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /organizations/1
  # PATCH/PUT /organizations/1.json
  def update
    respond_to do |format|
      if @organization.update(organization_params)
        format.html { redirect_to @organization, notice: 'Organization was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /organizations/1
  # DELETE /organizations/1.json
  def destroy
    @organization.destroy
    respond_to do |format|
      format.html { redirect_to organizations_url }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_organization
    @organization = Foswipe::Organization.find(params[:id])
    authorise_filter @organization
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def organization_params
    params.require(:organization).permit(:name)
  end
end

app/controllers/foswipe/products_controller.rb
class Foswipe::ProductsController < Foswipe::ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :authorise_filter, :only => [:index, :new, :create]
  # GET /products
  # GET /products.json
  def index
    @products = Foswipe::Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Foswipe::Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Foswipe::Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to products_url, notice: 'Product was successfully created.' }
        format.json { render action: 'show', status: :created, location: @product }
      else
        format.html { render action: 'new' }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to products_url, notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_product
    @product = Foswipe::Product.find(params[:id])
    authorise_filter @product
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def product_params
    params.require(:product).permit(:name)
  end
end

app/views/foswipe/tickets/_attachment_fields.html.erb
<p>
	<%= f.label :attachment_uid %>
	<%= f.file_field :attachment %>
</p>

app/views/foswipe/tickets/_form.html.erb
<div class="row">
	<div class="container">

		<div class="col-md-10">

			<div class="panel panel-primary">
				<div class="panel-heading">
					<h3 class="panel-title"><strong>New Ticket </strong></h3>
				</div>
				<div class="panel-body">

					<%= form_for(@ticket) do |f| %>
					<% if @ticket.errors.any? %>
					<div id="error_explanation">
						<h2><%= pluralize(@ticket.errors.count, "error") %> prohibited this ticket from being saved:</h2>

						<ul>
							<% @ticket.errors.full_messages.each do |msg| %>
							<li>
								<%= msg %>
							</li>
							<% end %>
						</ul>
					</div>
					<% end %>

					<section class="content">
						<div class="row">
							<!-- left column -->
							<div class="col-md-12">
								<!-- general form elements -->
								<div class="box box-primary">
									<div class="box-header">
										<h3 class="box-title">Create Ticket</h3>
									</div><!-- /.box-header -->
									<!-- form start -->
									<form role="form">
										<div class="box-body">
											<div class="form-group">
												<%= f.label :title %>
												<br>
												<%= f.text_field :title, :class => "form-control" %>
											</div>
											

										</div><!-- /.box-body -->
										<div class="form-group">

											<%= f.label :status %>
											<br />
											<%= f.select :status, Foswipe::Ticket.statuses, {},:class=>"selectpicker"  %>

											<br />
										</div>

										<div class="form-group">
											<li class=" dropdown_blank default_group field">

												<%= f.label :priority %>
												<br />
												<%= f.select :priority, Foswipe::Ticket.priorities, {},:class=>"selectpicker"  %>
											</li>
											<br />
										</div>

										<%= f.label :content %>
										<br />
										<%= f.text_area :content, :cols => "100", :rows => "10" %>

										<div class="form-group">
											<%= f.fields_for :attachments do |builder| %>
											<%= render "attachment_fields", :f => builder %>
											<% end %>
										</div>
										<% if @find%>
										<label> Assign an Agent</label>
										<br />
										<%= f.select "support_id", options_from_collection_for_select(@agents, "id", "first_name"), prompt: "Assign to Agent"  %>

										<% end %>
								</div>
								<%= f.submit :class => "btn btn-primary" %>
							</div><!-- /.box -->

							<% end %>

app/views/foswipe/tickets/edit.html.erb
<h1>Editing ticket</h1>

<%= render 'form' %>


<%= link_to 'Show', @ticket %> |
<%= link_to 'Back', tickets_path %>

app/views/foswipe/tickets/index.html.erb
<!-- MAILBOX BEGIN -->
<div class="mailbox row">
	<div class="col-xs-12">
		<div class="box box-solid">
			<div class="box-body">
				<div class="row">
					<% if current_user.admin_or_agent? %>
					<div class="col-md-2 col-sm-4">
						<%= form_tag(tickets_path, :method => :get) do %>
						<!-- BOXES are complex enough to move the .box-header around.
						This is an example of having the box header within the box body -->
						<div class="box-header">
							<i class="fa fa-filter"></i>
							<h3 class="box-title">FILTERS</h3>
						</div>
						<!-- compose message btn -->
						<!-- Navigation - folders-->
						<div style="margin-top: 15px;">
							<ul class="nav nav-pills nav-stacked">
								<li class="header">
									Agents
								</li>
								<% @agents.each do |a| %>
								<li>
									<label>
										<input type="checkbox" name="agents[]" value="<%= a.id%>" class="onclick" <%= "checked" if params[:agents] && params[:agents].include?(a.id.to_s) %>>
										&nbsp; &nbsp; &nbsp; <%= a.name%></label>
								</li>
								<% end%>
							</ul>
							<ul class="nav nav-pills nav-stacked">
								<li class="header">
									Groups
								</li>
								<% @group.each do |g| %>
								<li>
									<label>
										<input type="checkbox" name="groups[]" value="<%= g.id%>" class="onsubmit">
										&nbsp; &nbsp; &nbsp; <%= g.group_name%></label>
								</li>
								<% end%>
							</ul>
							<ul class="nav nav-pills nav-stacked">
								<li class="header">
									Created
								</li>
								<li>
									<select class="form-control onsubmit custome-select" data-minimum-results-for-search="100" data-selected-value="<%= params[:created_at] %>" id="created_at" name="created_at">
										<option value="">Any time</option>
										<option value="5.minutes.ago..Time.now">Within 5 minutes</option>
										<option value="15.minutes.ago..Time.now">Within 15 minutes</option>
										<option value="30.minutes.ago..Time.now" >Within 30 minutes</option>
										<option value="1.hours.ago..Time.now">Within 1 hour</option>
										<option value="4.hours.ago..Time.now">Within 4 hours</option>
										<option value="12.hours.ago..Time.now">Within 12 hours</option>
										<option value="24.hours.ago..Time.now">Within 24 hours</option>
										<option value="Time.now.beginning_of_day..Time.now.end_of_day">Today</option>
										<option value="1.day.ago.beginning_of_day..1.day.ago.end_of_day">Yesterday</option>
										<option value="Time.now.beginning_of_week..Time.now">This Week</option>
										<option value="Time.now.beginning_of_month..Time.now">This Month</option>
										<option value="2.months.ago.beginning_of_day..Time.now">Last 2 months</option>
										<option value="6.months.ago.beginning_of_day..Time.now">Last 6 months</option>
									</select>
								</li>
							</ul>
							<ul class="nav nav-pills nav-stacked">
								<li class="header">
									Due by
								</li>
								<li>
									<label class="item">
										<input type="checkbox" name="due_by[]" value="overdue" >
										&nbsp; &nbsp; &nbsp; Overdue</label>
								</li>
								<li>
									<label class="item">
										<input type="checkbox" name="due_by[]" value="overdue" >
										&nbsp; &nbsp; &nbsp; Today</label>
								</li>
								<li>
									<label class="item">
										<input type="checkbox" name="due_by[]" value="overdue" >
										&nbsp; &nbsp; &nbsp; Tomorrow</label>
								</li>
								<li>
									<label class="item">
										<input type="checkbox" name="due_by[]" value="overdue" >
										&nbsp; &nbsp; &nbsp; Next 8 hours</label>
								</li>
							</ul>

							<ul class="nav nav-pills nav-stacked">
								<li class="header">
									Status
								</li>
								<li>
									
									<select class="select2 filter_item onsubmit" id="status" multiple="multiple" name="status[]" placeholder="Select a status">
		 <% Foswipe::Ticket.statuses.each do|status| %>
		  <option value="<%= status %>" <%= 'selected="selected"' if params[:status] && params[:status].include?(status) %>><%= status %></option>
		  <% end %>
		 
</select>


								</li>
							</ul>
							<ul class="nav nav-pills nav-stacked">
								<li class="header">
									Priority
								</li>
								<% Foswipe::Ticket.priorities.each do |priority|%>
								<li>
									<label class="item">
										<input type="checkbox" name="priority[]" value="<%= priority %>" class="onclick" <%= "checked" if params[:priority] && params[:priority].include?(priority) %>>
										&nbsp; &nbsp; &nbsp; <%= priority %> </label>
								</li>
								<% end %>
							</ul>
							<ul class="nav nav-pills nav-stacked">
								<li class="header">
									Ticket Type
								</li>
								<li>
									<select class="select2 filter_item onsubmit" id="ticket_type" multiple="multiple" name="ticket_type[]" placeholder="Select ticket type">
										<option value="Question">Question</option>
										<option value="Incident">Incident</option>
										<option value="Problem" >Problem</option>
										<option value="Feature Request">Feature Request</option>
										<option value="Lead">Lead</option>
									</select>
								</li>
							</ul>
							<ul class="nav nav-pills nav-stacked">
								<li class="header">
									Ticket Source
								</li>
								<li>
									<select class="select2 filter_item onsubmit" id="source" multiple="multiple" name="source[]" placeholder="Select ticket source">
										<option value="1" >Email</option>
										<option value="2">Portal</option>
										<option value="3">Phone</option>
										<option value="4">Forum</option>
										<option value="5">Twitter</option>
										<option value="6">Facebook</option>
										<option value="7">Chat</option>
										<option value="8">MobiHelp</option>
										<option value="9">Feedback Widget</option>
									</select>
								</li>
							</ul>
							<ul class="nav nav-pills nav-stacked">
								<li class="header">
									Customer or Requestor
								</li>
								<li>
									<select class="select2 filter_item onsubmit" id="source" multiple="multiple" name="source[]" placeholder="Select ticket source">

									</select>
								</li>
							</ul>

						</div>

					</div><!-- /.col (LEFT) -->

					<div class="col-md-10 col-sm-9">
						<div class="row pad">
							<div class="col-sm-6">
								<label style="margin-right: 10px;">
									<input type="checkbox" id="check-all"/>
								</label>
								<!-- Action button -->
								<div class="btn-group">
									<button type="button" class="btn btn-default btn-sm btn-flat dropdown-toggle" data-toggle="dropdown">
										Action <span class="caret"></span>
									</button>
									<ul class="dropdown-menu" role="menu">
										<li>
											<a href="#">Mark as read</a>
										</li>
										<li>
											<a href="#">Mark as unread</a>
										</li>
										<li class="divider"></li>
										<li>
											<a href="#">Move to junk</a>
										</li>
										<li class="divider"></li>
										<li>
											<a href="#">Delete</a>
										</li>
									</ul>
								</div>

							</div>
							<div class="col-sm-6 search-form">
								<div  class="text-right">
									<div class="input-group">
										<input type="text" class="form-control input-sm" placeholder="Search" name = "search">
										<div class="input-group-btn">
											<button type="submit" name="q" class="btn btn-sm btn-primary">
												<i class="fa fa-search"></i>
											</button>
										</div>
									</div>
								</div>
							</div>
						</div><!-- /.row -->
						<% end %>
						<% end %>
						<div class="table-responsive">
							<!-- THE MESSAGES -->
							<table class="table table-mailbox">
								<% @tickets.each do |ticket| %>
								<tr>
									<td class="bg-aqua no-padding" style="width: 3px;"></td>
									<td class="small-col">
									<input type="checkbox" />
									</td>
									<td class="small-col">
									<div class="user-panel no-padding">
										<div class="image">
											<img src="http://www.gravatar.com/avatar/2da864f0202e0387adda7531651d8682" class="img-circle" alt="User Image">
										</div>
									</div></td>
									<td class="name"><h4 class="no-margin"><%= link_to ticket.title, ticket %></h4>
									<div>
										<input type="hidden" value="<%= ticket.created_at %>" id="<%= "#{ticket.id}_ago" %>"/>
										<h6 class=""><span class="text-muted">From:</span>&nbsp;&nbsp;<%= ticket.customer.name %>&nbsp;&nbsp;<span class="text-muted">Created:</span>&nbsp;&nbsp;<span class="days_ago" id="<%= ticket.id %>"> 9 </span> days ago</h6>
									</div>
									<div>
										<h6 class="" style="
										margin-bottom: 0px;
										">Overdue by 9 days</h6>
									</div></td>
									<td class="time" style="vertical-align: middle;"><small class="badge pull-right bg-red">overdue</small></td>
									<td class="name">
									<blockquote class="no-margin" style="padding: 0px 20px;float: left;">
										<%= form_for ticket do |f| %>
										<div class="pull-left" style="margin-right: 10px;">
											<h5 class="" style="
											margin-top: 0px;
											"><span class="text-muted">Agent:</span></h5>
											<h5><span class="text-muted">Status:</span></h5>
											<h5 style="margin-bottom: 0px;"><span class="text-muted">Priority:</span></h5>
										</div>

										<div class="pull-left">
											<h5 style="
											margin-top: 0px;
											"> <%= f.select :support_id, Foswipe::User.agents.collect{|a| [a.name, a.id]}, {},:class=>"form-control custome-form-control onsubmit"  %> </h5>
											<h5><%= f.select :status, Foswipe::Ticket.statuses, {},:class=>"form-control custome-form-control onsubmit"  %></h5>
											<h5 style="margin-bottom: 0px;"> <%= f.select :priority, Foswipe::Ticket.priorities, {},:class=>"form-control custome-form-control onsubmit"  %> </h5>
										</div>
										<% end %>
									</blockquote></td>
								</tr>
								<% end %>
							</table>
						</div><!-- /.table-responsive -->
					</div><!-- /.col (RIGHT) -->
				</div><!-- /.row -->
			</div><!-- /.box-body -->
			<div class="box-footer clearfix">
				<div class="pull-right">
					<small>Showing 1-12/1,240</small>
					<button class="btn btn-xs btn-primary">
						<i class="fa fa-caret-left"></i>
					</button>
					<button class="btn btn-xs btn-primary">
						<i class="fa fa-caret-right"></i>
					</button>
				</div>
			</div><!-- box-footer -->
		</div><!-- /.box -->
	</div><!-- /.col (MAIN) -->
</div>
<!-- MAILBOX END -->

app/views/foswipe/tickets/new.html.erb
<%= render 'form' %>
<br>
<!--
<div class="col-md-2"></div>
<%= link_to 'Back', clients_path, :class=>"btn btn-primary btn-sm" %>
-->